import type { ProjectSpec } from "./spec";

/**
 * The three demo projects. People, clients, and repositories are fictional.
 * See `expectations.ts` for the signals each project is scripted to produce.
 */

/** Healthy: steady velocity, on-track sprint, comfortable budget. */
export const ATLAS: ProjectSpec = {
  slug: "atlas",
  name: "Atlas Storefront",
  clientName: "Northwind",
  jiraKey: "ATL",
  githubRepo: "demo-org/atlas-web",
  boardId: "12",
  jiraSprintIdBase: 1180,
  sprintNumberBase: 18,
  prNumberBase: 101,
  people: [
    { name: "Lucía Fernández", login: "lucia-fernandez" },
    { name: "Martín Rossi", login: "martin-rossi" },
    { name: "Sofía Herrera", login: "sofia-herrera" },
    { name: "Diego Acosta", login: "diego-acosta" },
    { name: "Valentina Ruiz", login: "valentina-ruiz" },
  ],
  budgetAmount: 250_000,
  hourlyRate: 55,
  endOffsetDays: 120,
  forecastUnit: "points",
  wipLimit: 5,
  historySprints: 6,
  historyVelocity: { min: 32, max: 36 },
  titles: {
    Story: [
      "Product comparison table for up to four items",
      "Wishlist sharing via public link",
      "Recently viewed products carousel",
      "Multi-currency price display",
      "Gift wrapping option at checkout",
      "Store locator with opening hours",
      "One-click reorder from order history",
      "Customer reviews with photo uploads",
      "Bundle discounts on product page",
      "Accessible size guide modal",
      "Delivery date estimate on product page",
      "Split payment between gift card and card",
      "Search suggestions with typo tolerance",
      "Server-side feature flags for checkout experiments",
      "Category landing pages with curated collections",
      "Newsletter signup with double opt-in",
      "Order returns self-service flow",
      "Invoice PDF download",
      "Customer address book",
      "Product video gallery",
    ],
    Bug: [
      "Duplicate order confirmation emails",
      "Product images flicker on Safari",
      "Sort by price ignores sale prices",
      "Broken pagination on category pages",
      "Currency symbol wrong for CAD",
      "Wishlist count not updated after removal",
      "Infinite spinner when payment is declined",
      "Locale switch resets the cart",
      "Search returns archived products",
      "Cookie banner hides checkout button on mobile",
    ],
    Task: [
      "Upgrade Next.js to the latest minor",
      "Migrate image CDN configuration",
      "Remove legacy analytics snippet",
      "Add Lighthouse budget to CI",
      "Add structured logging to API routes",
      "Refactor price formatting helpers",
      "Document checkout state machine",
      "Set up visual regression snapshots",
      "Clean up unused feature flags",
      "Add contract tests for payment webhooks",
    ],
    Spike: [
      "Spike: evaluate headless CMS options",
      "Spike: passkeys for customer login",
      "Spike: payment provider failover",
      "Spike: server components for product pages",
    ],
  },
  activeSprintGoal: "Launch guest checkout and CSV invoice export for Northwind",
  activePlan: [
    { type: "Story", title: "Guest checkout with email confirmation", points: 5, assignee: 1, state: "done", startedOnDay: 1, doneOnDay: 2 },
    { type: "Story", title: "Promo code field with inline validation", points: 3, assignee: 2, state: "done", startedOnDay: 1, doneOnDay: 2 },
    { type: "Bug", title: "Cart total rounds incorrectly with percentage discounts", points: 2, assignee: 3, state: "done", startedOnDay: 2, doneOnDay: 2 },
    { type: "Task", title: "Add E2E tests for guest checkout", points: 3, assignee: 4, state: "done", startedOnDay: 2, doneOnDay: 3 },
    { type: "Story", title: "Export invoices to CSV from the account page", points: 5, assignee: 0, state: "done", startedOnDay: 2, doneOnDay: 4 },
    { type: "Bug", title: "Checkout button disabled after address edit", points: 2, assignee: 3, state: "done", startedOnDay: 4, doneOnDay: 5 },
    { type: "Story", title: "Order tracking timeline on order detail page", points: 3, assignee: 2, state: "in_review", startedOnDay: 3, prOnDay: 5 },
    { type: "Story", title: "Saved carts for signed-in customers", points: 3, assignee: 1, state: "in_progress", startedOnDay: 4 },
    { type: "Task", title: "Split checkout bundle to reduce JS size", points: 2, assignee: 4, state: "in_progress", startedOnDay: 5 },
    { type: "Story", title: "Address autocomplete in checkout", points: 3, assignee: 1, state: "todo" },
    { type: "Bug", title: "Session expires during payment redirect", points: 2, assignee: 3, state: "done", startedOnDay: 4, doneOnDay: 5 },
    { type: "Task", title: "Rotate payment provider webhook secret", points: 1, assignee: 0, state: "done", startedOnDay: 3, doneOnDay: 3 },
  ],
  backlog: [
    { type: "Story", title: "Loyalty points balance in header", points: 5, nextSprint: true },
    { type: "Story", title: "Back-in-stock email subscription", points: 3, nextSprint: true },
    { type: "Bug", title: "Missing alt text on promo banners", points: 1 },
    { type: "Spike", title: "Spike: edge caching for category pages", points: 2 },
  ],
  comments: [
    { planIndex: 0, author: 3, body: "Confirmation email template approved by Northwind marketing.", at: { day: 2, hour: 9.5 } },
    { planIndex: 4, author: 1, body: "Does the CSV need the tax breakdown per line?", at: { day: 2, hour: 10 } },
    { planIndex: 4, author: 0, body: "Yes. Northwind finance asked for net, tax, and gross per line.", at: { day: 2, hour: 11.5 } },
    // Scripted pending item: a question nobody answered for more than 48h.
    { planIndex: 7, author: 2, body: "Lucía, should saved carts expire after 30 days or persist until the customer clears them? I need this before finalizing the schema.", at: { daysAgo: 3, hour: 15.33 } },
  ],
  docs: [
    { slug: "atlas-adr-012-server-side-feature-flags", title: "ADR-012: Server-side feature flags for checkout experiments", excerpt: "Decision: evaluate flags on the server to avoid layout shift and keep experiment assignment consistent across devices. Status: accepted.", updatedDaysAgo: 20 },
    { slug: "atlas-release-checklist", title: "Release checklist: storefront web", excerpt: "Run the E2E checkout suite, verify the Lighthouse budget, confirm payment webhooks, and announce the release in the Northwind channel.", updatedDaysAgo: 9 },
    { slug: "atlas-runbook-checkout-incidents", title: "Runbook: checkout incidents", excerpt: "If payment confirmations stall, check the provider status page and the webhook queue depth; roll back the last deploy if errors exceed 2%.", updatedDaysAgo: 34 },
  ],
  // Next sprint only: no impact on the current sprint forecast.
  pto: [{ person: 4, days: [12, 13] }],
  burn: { kind: "steady", hoursPerPersonDay: 5 },
};

/** Sprint at risk: scope creep, PTO in the remaining days, WIP over limit. */
export const BEACON: ProjectSpec = {
  slug: "beacon",
  name: "Beacon Logistics API",
  clientName: "Globex",
  jiraKey: "BCN",
  githubRepo: "demo-org/beacon-api",
  boardId: "27",
  jiraSprintIdBase: 2240,
  sprintNumberBase: 9,
  prNumberBase: 201,
  people: [
    { name: "Tomás Medina", login: "tomas-medina" },
    { name: "Camila Ortega", login: "camila-ortega" },
    { name: "Nicolás Vega", login: "nicolas-vega" },
    { name: "Julieta Ramos", login: "julieta-ramos" },
    { name: "Bruno Castro", login: "bruno-castro" },
  ],
  budgetAmount: 200_000,
  hourlyRate: 50,
  endOffsetDays: 90,
  forecastUnit: "points",
  wipLimit: 5,
  historySprints: 6,
  historyVelocity: { min: 35, max: 39 },
  titles: {
    Story: [
      "Rate limiting per API key on /orders",
      "Shipment label PDF generation",
      "Address validation service integration",
      "Delivery exception notifications",
      "API key rotation endpoint",
      "Return merchandise authorization flow",
      "Warehouse capacity endpoint",
      "Order status webhooks v2",
      "Multi-parcel shipments",
      "Tracking events SSE stream",
      "OpenAPI examples for every endpoint",
      "Batch tracking lookup",
      "Tenant-level webhook configuration",
      "Carrier service level mapping",
      "Shipment cost breakdown in responses",
      "Sandbox environment for integrators",
      "Bulk label reprint endpoint",
      "Order notes with attachments",
    ],
    Bug: [
      "Timezone offset wrong in pickup windows",
      "Duplicate webhook deliveries after retry",
      "500 on /orders when notes exceed 1k chars",
      "Pagination cursor skips records on ties",
      "Wrong weight unit for EU carriers",
      "Stale cache after order cancellation",
      "Signature mismatch on webhook payloads with unicode",
      "Shipment search ignores status filter",
      "Memory leak in tracking poller",
      "Retry-After header missing on 429 responses",
    ],
    Task: [
      "Upgrade Node runtime to 22 LTS",
      "Add contract tests for carrier adapters",
      "Move secrets to the vault",
      "Enable structured request logging",
      "Refactor carrier adapter interface",
      "Rotate staging TLS certificates",
      "Add SLO alerts for webhook delivery",
      "Add p95 latency dashboards",
      "Clean up feature toggles for v2 webhooks",
      "Automate OpenAPI publishing",
    ],
    Spike: [
      "Spike: event sourcing for order history",
      "Spike: carrier API sandbox automation",
      "Spike: gRPC for internal services",
      "Spike: multi-region failover",
    ],
  },
  activeSprintGoal: "Ship idempotent order creation and cursor pagination for Globex",
  activePlan: [
    { type: "Story", title: "Idempotency keys for POST /orders", points: 5, assignee: 3, state: "done", startedOnDay: 1, doneOnDay: 2 },
    { type: "Story", title: "Cursor pagination for /shipments", points: 3, assignee: 4, state: "done", startedOnDay: 2, doneOnDay: 3 },
    { type: "Bug", title: "Rate limiter counts OPTIONS requests", points: 2, assignee: 0, state: "done", startedOnDay: 1, doneOnDay: 1 },
    { type: "Task", title: "Add database indexes for shipment search", points: 3, assignee: 2, state: "done", startedOnDay: 3, doneOnDay: 4 },
    // Scope creep: re-estimated 3 -> 5 after the sprint started (+2).
    { type: "Story", title: "Webhook retries with exponential backoff", points: 5, initialPoints: 3, reestimatedOnDay: 2, assignee: 1, state: "done", startedOnDay: 2, doneOnDay: 5 },
    // Scripted: carried over, In Progress, no commits for more than 5 days.
    { type: "Story", title: "Carrier rate quotes endpoint", points: 3, assignee: 2, state: "in_progress", carriedOver: true, script: "stalled" },
    // Scripted: PR waiting for a first review for more than 52 hours.
    { type: "Story", title: "Bulk shipment creation endpoint", points: 2, assignee: 3, state: "in_review", script: "stale_review" },
    { type: "Task", title: "Load test /orders at 500 rps", points: 1, assignee: 4, state: "in_progress", startedOnDay: 4 },
    { type: "Bug", title: "Health check reports OK when DB is down", points: 1, assignee: 0, state: "in_progress", startedOnDay: 5 },
    // Scope creep: re-estimated 2 -> 5 after the sprint started (+3).
    { type: "Story", title: "Partial order cancellation", points: 5, initialPoints: 2, reestimatedOnDay: 3, assignee: 1, state: "in_progress", startedOnDay: 2 },
    { type: "Task", title: "Document webhook error codes in the API reference", points: 1, assignee: 3, state: "in_progress", startedOnDay: 5 },
    { type: "Bug", title: "Label PDF cut off for long addresses", points: 1, assignee: 2, state: "in_review", startedOnDay: 4, prOnDay: 5 },
    // Scope creep: added after the sprint started (+5, expedited).
    { type: "Story", title: "Customs declaration fields for international orders", points: 5, assignee: 0, state: "done", addedOnDay: 2, startedOnDay: 2, doneOnDay: 4 },
    // Scope creep: added after the sprint started (+3).
    { type: "Task", title: "Usage metrics export for Globex billing", points: 3, assignee: 4, state: "in_progress", addedOnDay: 3, startedOnDay: 4 },
  ],
  backlog: [
    { type: "Story", title: "Scheduled pickups API", points: 5, nextSprint: true },
    { type: "Story", title: "Proof-of-delivery photo upload", points: 3, nextSprint: true },
    { type: "Task", title: "Remove deprecated v1 endpoints", points: 2 },
    { type: "Spike", title: "Spike: queue-based webhook delivery", points: 3 },
  ],
  comments: [
    { planIndex: 12, author: 0, body: "Globex asked for customs fields before the November release; the PO approved adding this mid-sprint.", at: { day: 2, hour: 10.75 } },
    { planIndex: 13, author: 3, body: "Added after the Globex steering call; billing needs the export before month end.", at: { day: 3, hour: 11 } },
    { planIndex: 5, author: 2, body: "Blocked on the carrier sandbox credentials. Globex is requesting them from the carrier.", at: { daysAgo: 5, hour: 11 } },
  ],
  orphanPullRequest: {
    title: "Hotfix: raise upstream timeout for carrier calls",
    branch: "hotfix-upstream-timeout",
    author: 4,
    openedOnDay: 3,
    mergedOnDay: 4,
  },
  docs: [
    { slug: "beacon-adr-007-rate-limiting", title: "ADR-007: Rate limiting per API key", excerpt: "Decision: token bucket per API key at the gateway, 100 requests per minute by default, configurable per Globex tenant. Status: accepted.", updatedDaysAgo: 41 },
    { slug: "beacon-release-checklist-api", title: "Release checklist: Beacon API", excerpt: "Update the OpenAPI spec, run contract tests against carrier sandboxes, and notify Globex integrators 48 hours before breaking changes.", updatedDaysAgo: 15 },
    { slug: "beacon-runbook-webhook-retries", title: "Runbook: webhook delivery failures", excerpt: "Inspect the dead-letter queue, replay events per tenant, and confirm signatures with the rotated secret.", updatedDaysAgo: 7 },
  ],
  // Two engineers out during the remaining sprint days.
  pto: [
    { person: 1, days: [7, 8] },
    { person: 2, days: [9, 10] },
  ],
  burn: { kind: "steady", hoursPerPersonDay: 5 },
};

/** Budget overrun: burn accelerates after two engineers join. */
export const COBALT: ProjectSpec = {
  slug: "cobalt",
  name: "Cobalt Data Platform",
  clientName: "Initech",
  jiraKey: "CBL",
  githubRepo: "demo-org/cobalt-etl",
  boardId: "41",
  jiraSprintIdBase: 3310,
  sprintNumberBase: 1,
  prNumberBase: 51,
  people: [
    { name: "Paula Giménez", login: "paula-gimenez" },
    { name: "Federico Molina", login: "federico-molina" },
    { name: "Carla Domínguez", login: "carla-dominguez" },
    { name: "Agustina Silva", login: "agustina-silva", joinsLate: true },
    { name: "Joaquín Navarro", login: "joaquin-navarro", joinsLate: true },
  ],
  budgetAmount: 120_000,
  hourlyRate: 60,
  endOffsetDays: 42,
  forecastUnit: "issues",
  wipLimit: 4,
  historySprints: 8,
  historyVelocity: { min: 28, max: 32 },
  titles: {
    Story: [
      "Incremental load for invoices table",
      "Backfill 2024 ledger data",
      "Partition fact_sales by month",
      "CDC ingestion for customers",
      "Data quality checks on order lines",
      "Slowly changing dimension for products",
      "Daily revenue mart for finance",
      "Currency conversion dimension",
      "Lineage metadata export",
      "Reprocessing tool for failed batches",
      "Supplier dimension consolidation",
      "Retention policy for raw zone",
      "Self-serve dataset catalog entries",
      "Customer churn features table",
      "Warehouse usage dashboard",
      "Data contracts for upstream teams",
    ],
    Bug: [
      "Duplicate rows after retrying invoice load",
      "Timezone drift in daily partitions",
      "Null customer ids in fact_sales",
      "Decimal precision loss in currency amounts",
      "Backfill job exceeds memory limit",
      "Wrong row counts in reconciliation report",
      "Schema drift breaks customers CDC",
      "Late partitions not picked up by mart refresh",
    ],
    Task: [
      "Upgrade orchestrator to latest release",
      "Add unit tests for transformation macros",
      "Tune warehouse cluster size",
      "Rotate service account keys",
      "Document the raw-to-mart layering",
      "Add CI checks for SQL linting",
      "Create staging environment seed",
      "Review warehouse access roles",
    ],
    Spike: [
      "Spike: SQL transformation framework options",
      "Spike: cost model for warehouse auto-scaling",
      "Spike: column-level lineage tooling",
    ],
  },
  activeSprintGoal: "Cut over invoices and inventory to the new platform",
  activePlan: [
    { type: "Story", title: "Reconciliation report against source ERP", points: 5, assignee: 0, state: "done", startedOnDay: 1, doneOnDay: 3 },
    // Scripted pending item: Done, requires code, but no linked merged PR.
    { type: "Bug", title: "Scheduler skips runs after DST change", points: 2, assignee: 1, state: "done", startedOnDay: 2, doneOnDay: 4, script: "done_without_pr" },
    { type: "Task", title: "Set up alerting for failed DAGs", points: 2, assignee: 2, state: "done", startedOnDay: 1, doneOnDay: 2 },
    { type: "Story", title: "Inventory snapshot pipeline", points: 3, assignee: 3, state: "done", startedOnDay: 2, doneOnDay: 4 },
    { type: "Bug", title: "Orphaned temp tables after failures", points: 1, assignee: 4, state: "done", startedOnDay: 3, doneOnDay: 5 },
    { type: "Story", title: "Freshness SLA monitoring per table", points: 5, assignee: 1, state: "in_progress", startedOnDay: 3 },
    { type: "Story", title: "PII masking in staging tables", points: 3, assignee: 2, state: "in_review", startedOnDay: 2, prOnDay: 5 },
    { type: "Task", title: "Migrate legacy cron jobs to orchestrator", points: 2, assignee: 3, state: "in_progress", startedOnDay: 4 },
    { type: "Story", title: "Cost attribution tags per pipeline", points: 3, assignee: 4, state: "todo" },
    { type: "Spike", title: "Spike: open table format evaluation", points: 2, assignee: 0, state: "done", startedOnDay: 3, doneOnDay: 5 },
  ],
  backlog: [
    { type: "Story", title: "Late-arriving facts handling", points: 5, nextSprint: true },
    { type: "Task", title: "Archive legacy ETL scripts", points: 2, nextSprint: true },
    { type: "Bug", title: "Incorrect week numbering in revenue mart", points: 2 },
    { type: "Spike", title: "Spike: streaming vs micro-batch for CDC", points: 2 },
  ],
  comments: [
    { planIndex: 0, author: 0, body: "Agustina and Joaquín joined three weeks ago to hit the migration milestone; burn stays higher until cut-over.", at: { day: 1, hour: 9.5 } },
    { planIndex: 1, author: 1, body: "Applied the fix directly on main to unblock the nightly load; will open a follow-up PR with tests.", at: { day: 4, hour: 16.5 } },
  ],
  docs: [
    { slug: "cobalt-adr-003-incremental-loads", title: "ADR-003: Incremental loads with change data capture", excerpt: "Decision: replace nightly full reloads with CDC-based incremental loads for invoices and customers to cut warehouse cost. Status: accepted.", updatedDaysAgo: 60 },
    { slug: "cobalt-adr-004-monthly-partitions", title: "ADR-004: Partition fact tables by month", excerpt: "Decision: partition fact_sales and fact_invoices by month; every query must filter on the partition column. Status: accepted.", updatedDaysAgo: 25 },
    { slug: "cobalt-runbook-nightly-etl", title: "Runbook: nightly ETL failures", excerpt: "Check the orchestrator run log, re-run failed tasks with the reprocessing tool, and verify row counts in the reconciliation report.", updatedDaysAgo: 12 },
  ],
  pto: [],
  burn: {
    kind: "accelerating",
    hoursPerPersonDay: 5,
    windowWorkingDays: 15,
    exhaustionWorkingDaysAhead: 20,
  },
};

export const DEMO_PROJECT_SPECS: readonly ProjectSpec[] = [ATLAS, BEACON, COBALT];
